ARDUINO_DIR   = /usr/share/arduino
#ARDMK_DIR     = /usr/share/arduino
ARDMK_DIR     = ~/TRoll/projects/arduino_makefile/arduino-mk
ARDMK_PATH    = ~/TRoll/projects/arduino_makefile/bin
AVR_TOOLS_DIR = /usr


BOARD_TAG = mega2560
#BOARD_TAG = atmega1280
MONITOR_PORT = /dev/ttyUSB0
MONITOR_BAUDRATE = 115200
ARDUINO_LIBS = 

CPPFLAGS += -Wextra
#CPPFLAGS += -Wextra -Werror

include $(ARDMK_DIR)/Arduino.mk
